// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg6y6w7xeyQinp-Y88egx_aelVJVRA830',
    appId: '1:473584687483:web:ca6a1170c90501401585de',
    messagingSenderId: '473584687483',
    projectId: 'musiser-bb175',
    authDomain: 'musiser-bb175.firebaseapp.com',
    storageBucket: 'musiser-bb175.appspot.com',
    measurementId: 'G-V0XENB5Z75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnVoJKK_3UccwzLgC7YlUbB3NJ3FHjM2s',
    appId: '1:473584687483:android:6c4d7a378077708a1585de',
    messagingSenderId: '473584687483',
    projectId: 'musiser-bb175',
    storageBucket: 'musiser-bb175.appspot.com',
  );
}
